### ISSUE TITLE
Error en Bluetooth

### ISSUE THREAD

**Issue by ZaydelSenpai** [daviiid99/LineageOS-Switch-T210#1]
Primero que nada muy buenas David, Gracias por compartir tu modificación para Nintendo Switch!
Quería saber si también tienes problemas con el Bluetooth, todo el tiempo me dice que "sigue fallando"
Sabes algo? Muchas Gracias y suerte!

**Comment by daviiid99** [comment]
Es un error conocido, las fuentes de switchroot están rotas desde hace días.

Unas builds tienen fallos de bluetooth que parece ser persistente y otras como androidTV (Foster) están rotas desde el 28/12

Publicaré nuevas builds pronto, así que haré pruebas aunque no he visto ninguna commit nueva que arregle ese fallo aún.
Habrá que esperar unas semanas a que las fuentes sean más estables, ni siquiera se ha lanzando aún una build oficial estable y no parece ser inminente con estos Bugs

Un saludo

**Comment by damolmo** [comment]
> Primero que nada muy buenas David, Gracias por compartir tu modificación para Nintendo Switch!
> Quería saber si también tienes problemas con el Bluetooth, todo el tiempo me dice que "sigue fallando"
> Sabes algo? Muchas Gracias y suerte!

Es un error conocido, las fuentes de switchroot están rotas desde hace días.

Unas builds tienen fallos de bluetooth que parece ser persistente y otras como androidTV (Foster) están rotas desde el 28/12

Publicaré nuevas builds pronto, así que haré pruebas aunque no he visto ninguna commit nueva que arregle ese fallo aún.
Habrá que esperar unas semanas a que las fuentes sean más estables, ni siquiera se ha lanzando aún una build oficial estable y no parece ser inminente con estos Bugs

Un saludo
