### ISSUE TITLE
android tv version not working

### ISSUE THREAD

**Issue by tesla-k** [daviiid99/LineageOS-Switch-T210#10]
Thank you, you are using your rom files well.
I am using android tv+nvidia version.
Only the 20201228 version works fine.
Both 20210111 and 20210102 do not work.
I changed the memory card, but it is the same.
I uploaded the ROM file more than 20 times, but the boot screen does not appear.
data and cache were mounted normally.
Please check the ROM file.

There is one more desperate request, I hope that you can build with user, release-keys version.
Your ROM file is recognized as rooted. So, important applications do not run.

thank you. Bro.

**Comment by damolmo** [comment]
Just use 20201228 version for now
I'll try to fix the build in the next release

Sources are broken for androidTV

**Comment by Keriam** [comment]
Last work build is 28th december for ATV version.

Could you give more details about changes in this version ? ("Add fan profile paths to uevent config")

What is it exactly ?
Is it an implementation of Fan profile in ATV build like vanilla build ?

Here the new settings : 
"# Fan profiles
/sys/devices/thermal-fan-est fan_profile 0660 system system
/sys/devices/pwm-fan fan_profile 0660 system system"

Thanks

**Comment by astrit-veliu** [comment]
Which Hekate version are you using currently because i didn't even got the splash screen
