### ISSUE TITLE
Bluetooth issue.

### ISSUE THREAD

**Issue by williamania** [daviiid99/LineageOS-Switch-T210#11]
Hello,
I found issue "bluetooth keeps stopping" after flashing new rom on Samsung 512GB Evo Plus Micro SD Card. Flashing on Samsung 256GB Evo Plus Micro SD Card bluetooth working fine. There is any card size limit for Andriod rom? Thank you

**Comment by roundaboutluke** [comment]
Edit: See you have reported directly to devs so 👍 https://switchroot.org/

**Comment by williamania** [comment]
Hi yes I have reported directly to devs. Waiting for response. 
Thanks

**Comment by damolmo** [comment]
> Hello,
> I found issue "bluetooth keeps stopping" after flashing new rom on Samsung 512GB Evo Plus Micro SD Card. Flashing on Samsung 256GB Evo Plus Micro SD Card bluetooth working fine. There is any card size limit for Andriod rom? Thank you

There's a fix 
Create this file and put a random MAC on it
https://gitlab.com/switchroot/android/android_device_nvidia_foster/-/commit/931399b01c4b89ce6e8d5695d18f53d4c6f42374#fb7d89cf71ae0fbb118ce817a32018d7bc5dcb2e

Or wait for Switchroot to fix it

**Comment by williamania** [comment]
Hi, l tried to figure out how to use a fix that you posted. But l don't have enough skills. Can you post small institution or add fix to your next release. I use Vanilla+NVIDIA rom. Thank you.
