### ISSUE TITLE
Bulild rota

### ISSUE THREAD

**Issue by Marietuno** [daviiid99/LineageOS-Switch-T210#14]
La ultima build que ahs subido está totalmente rota, el touch funciona en modo apaisado mientras que la pantalla se muestra en modo vertical, y a mayores el link de referencia a la release está mal.

**Comment by damolmo** [comment]
La build no está rota, es que el bootloader ha sido actualizado

Es necesario hacer un wipe del system o una instalación limpia o tendrás siempre ese problema

Yo uso la misma build de la release sin problemas, como puedes ver en la captura
![Screenshot_20210123-100539_Settings](https://user-images.githubusercontent.com/22205011/105614284-bd8e6400-5dc8-11eb-8763-d76baae82e4f.png)

**Comment by Crazymike76** [comment]
Funciona perfecta al flashear con el nuevo twrp y reemplazar los archivos del archivo Zip the hekate. Perdón por abrir el issue, debería haber reemplazado todo en vez de hacer dirty flash.
Gracias por las builds!

**Comment by Marietuno** [comment]
He hecho wipe de todo y al instalarla de nuevo sigue haciendo lo que te he dicho, a mayores del fallo del bluetooth. No se si se me escapa algo

**Comment by Crazymike76** [comment]
Marietuno, a mi me pasaba lo mismo que a ti. He reemplazado los archivos de la carpeta hekate en la SD, he entrado en hekate y he vuelto a hacer flash android desde el gestor de particiones. Luego he instalado la build nueva con las gapps y funciona todo bien. El bluetooth tb funciona bien. Espero que te sirva de ayuda.

**Comment by Marietuno** [comment]
Ya me funciona la orientacion de la pantalla, pero sigo sin conseguir que el bluetooth funcione, y he hecho lo que has dicho de actualizar el bootloader. He leido por ahí que con sd de "X" tamaño de almacenamiento, el tema del bluetooth se bugea, aunque no se cual sera el motivo. Por curiosidad que tamaño de sd teneis vosotros?

**Comment by Crazymike76** [comment]
Yo uso una SD de 256gb.

**Comment by Marietuno** [comment]
Pues no tengo  ni idea de cual puede ser la razon. Hago todos los wipes, y posteriormente instalo la rom. Luego le doy a reiniciar en vez de hacer wipe de dalvik y caché. No se si eso tiene algo que ver. A mayores tampoco instalo gapps ni el magisk porque solo la estoy testeando de momento

**Comment by JaviBonilla** [comment]
A mí me aparece el siguiente error en el paso 8, al instalar el zip, alguna idea de como solucionarlo?

```
Update process ended with ERROR: 7
Error installing zip file '/external_sd/lineage-17.1-202110122-UNOFFICIAL-forter_tab-daviiid99.zip'
```

La versión anterior se instala bien, gracias.

**Comment by JaviBonilla** [comment]
> A mí me aparece el siguiente error en el paso 8, al instalar el zip, alguna idea de como solucionarlo?
> 
> ```
> Update process ended with ERROR: 7
> Error installing zip file '/external_sd/lineage-17.1-202110122-UNOFFICIAL-forter_tab-daviiid99.zip'
> ```
> 
> La versión anterior se instala bien, gracias.

He vuelto a copiar el archivo a la SD y ahora no me ha dado ningún error, seguramente fuera un error en la copia del archivo.

**Comment by Marietuno** [comment]
He probado de todo y sigue sin funcionar el bluetooth, pero veo que has posteado una solución al tema en otro "Issue".
El problema es que no tengo suficientes conocimientos como para entenderlo, si pudieras explicármelo te lo agradecería eternamente. @daviiid99
