### ISSUE TITLE
Android doesn't boot after latest update

### ISSUE THREAD

**Issue by Cyber-Snake** [daviiid99/LineageOS-Switch-T210#17]
Installed latest Nvidia + Shield build and now Android doesn't boot, I see very long LineageOS loading and after that is just reboots back to TWRP. I installed update following instructions and wiped system partition, what can be the issue? Previous build installed without any problems.

**Comment by damolmo** [comment]
Probably you missed something, try again and download both files from the last release
I tested foster and foster_tab on my switch, both booted
![Screenshot_20210126-001309_Ajustes](https://user-images.githubusercontent.com/22205011/106004840-e6a64180-60b3-11eb-9038-d7abb46d2c7f.png)

**Comment by damolmo** [comment]
I think I know wthat's your issue
My switch went to a bootloop after flashing GApps or Magisk

A first reboot is needed before installing add-ons on twrp
