### ISSUE TITLE
Fallo bluetooth

### ISSUE THREAD

**Issue by Marietuno** [daviiid99/LineageOS-Switch-T210#19]
> Hello,
> I found issue "bluetooth keeps stopping" after flashing new rom on Samsung 512GB Evo Plus Micro SD Card. Flashing on Samsung 256GB Evo Plus Micro SD Card bluetooth working fine. There is any card size limit for Andriod rom? Thank you

There's a fix 
Create this file and put a random MAC on it
https://gitlab.com/switchroot/android/android_device_nvidia_foster/-/commit/931399b01c4b89ce6e8d5695d18f53d4c6f42374#fb7d89cf71ae0fbb118ce817a32018d7bc5dcb2e

Or wait for Switchroot to fix it

_Originally posted by @daviiid99 in https://github.com/daviiid99/LineageOS-Switch-T210/issues/11#issuecomment-764605543_

**Comment by Marietuno** [comment]
Podrías explicar esta solución para gente sin mucha habilidad con el código, como yo, para entender bien lo que hay que hacer?
Gracias

**Comment by williamania** [comment]
Hello, guy form switchroot discord send me this instruction.
![IMG_20210128_222553](https://user-images.githubusercontent.com/76970036/106208940-17719e00-61bc-11eb-8bf7-0aa0bea585c1.jpg).     

I done new android rom flash on 512gb card, after booting my bluetooth keeps stopping. I boot to atmosphere emunand (or if you have just atmosphere) and pair joycons  this will write bluetooth Mac. Then boot to hekate and select NYX options. 
![IMG_20210128_210618](https://user-images.githubusercontent.com/76970036/106209864-b34fd980-61bd-11eb-8f55-a97fb03cad32.jpg).   

Then dump Joy-con BT. 
![IMG_20210128_210006](https://user-images.githubusercontent.com/76970036/106209991-ea25ef80-61bd-11eb-8c16-e568771c6f8f.jpg)

2 files will be save in switchroot folder. Boot android bluetooth should work. You may be need wipe all your android partitions in twrp and flash rom again.  
Thank you for posting android roms updates Daviiid99 Muchas Gracias.

**Comment by Marietuno** [comment]
i tried several times... that's anoying but i can't fix it

**Comment by williamania** [comment]
Hi, l use LineageOS + NVIDIA build 20210125. When l flash, l only mount memory card rest are not available (l don't use wipe option). Then install select rom and add GApps.zip file then swipe to install. Boot to Android bluetooth not working. Restart and boot atmosphere disconnect joy-cons and pair them wirelessly. Boot hekate and dump joy-cons bt, 2 files will saved in switchroot. Check do you have then same kind files.
![IMG_20210130_061526](https://user-images.githubusercontent.com/76970036/106352408-de7c1b00-62da-11eb-98e9-fd5bddcde4bd.jpg) Bluetooth working, don't need pair joy-cons in Android they will connect automatically. Hope this will help, if not send more info how you flash your rom and which one are you using 👍

**Comment by damolmo** [comment]
Thanks guys for the bluetooth fix, I'll add this to README and close this issue
