### ISSUE TITLE
Failed To Mount Vendor/other partitions (TWRP 3.4.0 bug with Hekate repartition)

### ISSUE THREAD

**Issue by OfficialMT22** [daviiid99/LineageOS-Switch-T210#2]
how do i mount the vendor

**Comment by daviiid99** [comment]
If your vendor partition is fucked, flash the ROM and it will be okay

Also you may need to change the filesystem of your /data and /cache partitions to EXT2 and EXT4 or TWRP will not recognize them.

**Comment by damolmo** [comment]
> how do i mount the vendor

If your vendor partition is fucked, flash the ROM and it will be okay

Also you may need to change the filesystem of your /data and /cache partitions to EXT2 and EXT4 or TWRP will not recognize them.

(Go to WIPE on TWRP, select both /cache and /data and set the filesystem to EXT2 first, mount the partitions and return the filesystem type of the partitions to EXT4)
