### ISSUE TITLE
Endless paring of bluetooth accessories on android TV

### ISSUE THREAD

**Issue by kisars** [daviiid99/LineageOS-Switch-T210#20]
Installed latest  Android TV 20210126 version and couldnt pair neither to joycons nor to bluetooth keyboard , what makes impossible to use android tv

**Comment by kisars** [comment]
bluetooth fix mentioned in readme doesn't have any effect

**Comment by damolmo** [comment]
Weird, my joycons pair correctly on latest androidTV

**Comment by damolmo** [comment]
Can you get a log?
