### ISSUE TITLE
1.4Ghz

### ISSUE THREAD

**Issue by MaSieS4Fun** [daviiid99/LineageOS-Switch-T210#21]
Buenas, a ver tu sistema es fantástico en todos los aspectos y mejor funcional que la versión 8.1.
1- Puedo pasar archivos por USB puntazo
2- No tengo problemas en la configuración de los joy-con con según que emuladores
Y un largo etc. de mejoras respecto a la versión 8.1
la única pega que tiene que hace que me eche a tras de ponerlo en mi switch, es que no me deja pasar de 1.4Ghz en el clock de la CPU, incluso en modo root. Y dado que este aparato puede correr emuladores como citra y dolphin la diferencia de rendimiento que hay en tenerlo a 1.7 a 1.4Ghz es considerable.
sería interesante que en un futuro solucionaras esto, ya que haría tutoriales recomendado tu Android.
Un saludo y gracias por tu trabajo.
P.D: Si se pudiera poner hasta 2Ghz se podría jugar decente a juegos de Wii a 1.7Ghz no se puede. Ya lo miraras.  <- esto ya sería un extra :P

**Comment by damolmo** [comment]
Ya hice varias builds con OC pero dado que LineageOS 17.1 aún no es estable no quiero poner en riesgo consolas que acaben brickeadas

**Comment by MaSieS4Fun** [comment]
no te preocupes, esperaremos, y gracias.

**Comment by damolmo** [comment]
Si te da igual que este un poco desactualizado esta va a 2GHz

https://github.com/daviiid99/LineageOS-Switch-T210/releases/tag/20210111.3

**Comment by MaSieS4Fun** [comment]
Esla versión la probé y en modo root no me dejaba poner más de 1.4Ghz
las apps en modo root que use son: 
Performance tweaker y 3C CPU manager
de todas formas la probare con una SD limpia que no hiciera algo mal.
Te comento. Y gracias.

**Comment by damolmo** [comment]
Dudo que esas apps funcionen en la Switch

Yo usaría magisk y smartpack

**Comment by MaSieS4Fun** [comment]
Esta tarde lo pruebo, si ves por la ventana una seta nuclear…. Es que me ha explotado la consola xDD

**Comment by MaSieS4Fun** [comment]
no hay manera, te dejo el "vídeo" que he hecho para que lo veas.
https://www.youtube.com/watch?v=t2xGndmLdUI

No tengo nada de prisa si lo puedes hacer incluiré tu Android en mis tutoriales.
El tutorial de citra que hice pero con 8.1 por lo de la CPU. A partir del minuto 6:20
https://www.youtube.com/watch?v=6pM3SQATd1U
No hace falta llegar a los 2Ghz, tan solo el máximo natural de la switch 1785Mhz.
tu tranquilo si lo haces ya me contaras.

Saludos y gracias.

**Comment by damolmo** [comment]
Si se resetea automáticamente al aumentar la frecuencia es algo que no depende de mí, sino que puede ser cosa del governor o magisk

La build tiene habilitado el OC a 2GHz

**Comment by MaSieS4Fun** [comment]
no, no resetea, mírate el video.. intento poner 1.7 y se pone automáticamente a 1.4. si se reseteara lo encontraría normal. pero eso no pasa. míratelo con calma.
no hay prisa tengo el 8.1 funcionando bien. tuve que hacer cosas raras para hacer funcionar los sticks de lo mandos en el CITRA, cosa que con tu sistema no pasa. Y también cosas raras para meter las roms ahí.
Ya te digo tu sistema a nivel de configuración esta muy optimizado. la única pega es que no puedo aumentar el reloj de la CPU más de 1.4Ghz. si la pudiera poner 1785Mhz usaría tu release y estaría como un buitre a la expectativa de nuevas updates. 
te lo digo para que sea más funcional. y la use más gente.

**Comment by MaSieS4Fun** [comment]
He probado la “versión oficial” que ha dejado nuestro amigo y pasa lo mismo. No se puede pasar de 1.4GHz.
Probado lo probado :P tu versión va mejor ^^
saludos ;D

**Comment by damolmo** [comment]
> He probado la “versión oficial” que ha dejado nuestro amigo y pasa lo mismo. No se puede pasar de 1.4GHz.
> Probado lo probado :P tu versión va mejor ^^
> saludos ;D

Las fuentes son las mismas así que mis builds no oficiales y las oficiales comparten los mismos bugs.

Yo seguire haciendo builds y miraré lo del overclock a ver si puedo forzarlo

**Comment by MaSieS4Fun** [comment]
A ver… quería hacer un video versus Android 8.1 y Android 10 enseñando lo del overclock.
Me he dado cuenta de que instalando el “performance tweaker” este te hace instalar el “magisk” como dijiste.
Bueno ese no es el caso. El caso es que al iniciar Android 10 por primera vez en modo root abres la app “performance tweaker” y ahí no te deja pasar de 1428Mhz. Pero poniendo el CPU “maxium frequency”  a 1785Mhz aun la vuelva a dejar a 1428Mhz al reiniciar Android 10 parece ser que la deja a 1785Mhz. Luego sí que ya puedes jugar con las “frequencies” de la CPU.
hare unos test esta mañana y te comento

**Comment by MaSieS4Fun** [comment]
Si David, es como te digo. ya lo he grabado haciendo una instalación compartida ambos sistemas, el Android y el de Nintendo Switch. te pasar el vídeo. Te diré el minuto exacto para que lo veas. Te da un “falsa” sensación de que no se puede. Pero solo no se puede en esa sesión. Si alguien te lo pide se lo muestras. Saludos y gracias por la paciencia.

**Comment by MaSieS4Fun** [comment]
EL primer minuto y medio es donde se vela diferencia de rendimiento con el emulador.
luego para que veas lo que pasa con la CPU ve al minuto 17:07 y veras la magia.
https://www.youtube.com/watch?v=CPCZv2ebV5k
lo he solucionado así. disculpa las molestias y muchas gracias.

**Comment by damolmo** [comment]
Me alegro que todo se solucionara así de fácil 👍
