### ISSUE TITLE
Switchroot Android Q release is out

### ISSUE THREAD

**Issue by EmmmaTech** [daviiid99/LineageOS-Switch-T210#22]
Hello, to anyone who visits this repo at all, don't download a build from here. Instead, download the official release build from switchroot.org.

To the repo owner, you should probably take this repo down since there is no use for it anymore.

**Comment by damolmo** [comment]
There's no need to close this repo, i'll continue building unoffcial builds
But thanks for the update

**Comment by EmmmaTech** [comment]
No problem! I respect if you want to continue posting unofficial builds
