### ISSUE TITLE
Take down the LineageOS 18.1 builds

### ISSUE THREAD

**Issue by EmmmaTech** [daviiid99/LineageOS-Switch-T210#26]
Switchroot Android R (or LineageOS 18.1) is in an alpha state of testing. Because of this, there can be many unaddressed issues. This is not officially handled by switchroot, or is being released soon.

Please take down the builds. If you don't want to, you need to add a disclaimer.

**Comment by EmmmaTech** [comment]
#25 is a sorta similar request to this issue

**Comment by damolmo** [comment]
Okay, I'll add the disclaimer
