### ISSUE TITLE
"Bluetooth" App Dies

### ISSUE THREAD

**Issue by H-Kz** [daviiid99/LineageOS-Switch-T210#27]
I installed `LineageOS-17.1-20210218-Vanilla + NVIDIA` on my Switch, then the Android notify me `"Bluetooth keeps stopping"` for many times while Bluetooth turns on.
It wasn't happen when I installed `icosa-tablet-20210205-rel.zip` from https://download.switchroot.org/android-10/
 
Is there anyone having solution?

Thankyou

**Comment by damolmo** [comment]
Bluetooth needs a manual config, please follow https://github.com/daviiid99/LineageOS-Switch-T210#how-to-fix-bluetooth-keeps-stopping-english-instructions

**Comment by H-Kz** [comment]
Oh, I've skipped reading it. Sorry to trouble you and thank you for telling me it.
