### ISSUE TITLE
Password needed

### ISSUE THREAD

**Issue by williamania** [daviiid99/LineageOS-Switch-T210#5]
I flashed latest LineageOS + NVIDIA but asked me: To start Andriod, enter your password. I tried 0000 but not working I can't skip this.Thank you.

**Comment by damolmo** [comment]
Maybe something wrong happened in the flash process.
Please try again with a clean install

My builds are clean builds without any encryption

**Comment by williamania** [comment]
![1610140723795893895497847678919](https://user-images.githubusercontent.com/76970036/104065276-62b91200-51f7-11eb-9c55-a8f9445dcc42.jpg)

I flashed new rom from scratch on new micro SD card and this message appear enter your password. Some reason there is problem with new hekate 5.5.2 with version 5.5.1 installation finished successful. Thank you for your help.

**Comment by seyo-IV** [comment]
having the same problem. Reflashing didt help.

Wiped all storage, set filesystem ,reflashed, still asking for password.

**Comment by seyo-IV** [comment]
Ok I had to press format data under the wipe options

**Comment by williamania** [comment]
Use new hekate 5.5.3 problem was fixed in this release.
