### ISSUE TITLE
/data will not mount or change filesystem in TWRP

### ISSUE THREAD

**Issue by oblimode** [daviiid99/LineageOS-Switch-T210#6]
hi, not sure if i've missed anything here, i'm not fully experienced with TWRP or switch modding. i made sure to follow the instructions and found myself having to change the filesystems of data and cache. i fixed cache and got it to mount with no issues but i found that trying to change the filesystem of data immediately restarts TWRP, with the filesystem having not changed and data still being unable to mount.

**Comment by damolmo** [comment]
Did you try to flash the rom first?
