### ISSUE TITLE
Power button does nothing

### ISSUE THREAD

**Issue by HiddenHorcrux** [daviiid99/LineageOS-Switch-T210#8]
As title says, power button doesnt do anything in latest build. Doesnt put android to sleep and when android goes to sleep automatically you cant wake it up, a full reboot is required to get it running again

**Comment by damolmo** [comment]
Didn't face this issue in my Switch

Anyway these are test builds with the latest sources form switchroot, new commits can break/solve things

I'll build new builds when new changes comes out

**Comment by HiddenHorcrux** [comment]
Seems to work perfectly now, not sure what went on
