### ISSUE TITLE
Joy-Con Rail Stops Working At Deep Sleep Wake

### ISSUE THREAD

**Issue by HiddenHorcrux** [daviiid99/LineageOS-Switch-T210#9]
When the OS enters sleep mode the joy-cons attached to the system no longer work until you do a system reboot.

**Comment by damolmo** [comment]
Thanks for reporting this issue

Probably the joycon patch caused this issue, I'll try to remove it in the next builds

**Comment by HiddenHorcrux** [comment]
It only happens after waking the OS from a deep sleep, when you just wake it up from a non deep sleep the joy con rails still respond

**Comment by damolmo** [comment]
Fixed on latest release
